@startuml ReadingCurrentAlarmsFromLive
skinparam responseMessageBelowArrow true

title
RequestForProvidingAlarmsForLivenetviewCausesReadingCurrentAlarmsFromLive
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-alarms-for-livenetview" as Livenetview_Alarms
participant "MWDI://core-model-1-4:network-control-domain=live/control-construct={mountName}/alarms-1-0:alarm-pac/current-alarms" as CurrentAlarmsLive

LinkVis -> Livenetview_Alarms: {MountName, LinkId} (apiKeyAuth)

note over Livenetview_Alarms
Number of requests to be executed in parallel shall not exceed the value stated in
<b>profile=APTP-1-0-1-integer-p-005</b>
<b>IntegerProfilePac::IntegerProfileConfiguration:integerValue</b>
end note

activate Livenetview_Alarms
Livenetview_Alarms -> CurrentAlarmsLive: {MountName}(apiKeyAuth)
CurrentAlarmsLive --> Livenetview_Alarms: {entire list of active alarms form live}

deactivate Livenetview_Alarms

@enduml