@startuml DeterminingAirInterfaceUnderTest
skinparam responseMessageBelowArrow true

title
RequestForProvidingConfigurationForLiveNetViewCausesDeterminingAirInterfaceUuidUnderTest
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-configuration-for-livenetview" as APTP_Config
participant "<i>RequestForProvidingConfigurationForLivenetviewCausesReadingLtpStructure</i>" as LTPs
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}/\nltp-augment-1-0:ltp-augment-pac?fields=external-label" as ExternalLabel

LinkVis -> APTP_Config: {MountName, LinkId} (apiKeyAuth)
activate APTP_Config

LTPs --> APTP_Config: {Uuid, LocalId, LayerProtocolName}

note over APTP_Config
For all UUIDs with LayerProtocolName == AirLayer
until (9 first characters of ExternalLabel) == LinkId
end note

APTP_Config -> ExternalLabel: (apiKeyAuth)
ExternalLabel --> APTP_Config: {ExternalLabel}

note over APTP_Config
UuidUnderTest/LocalIdUnderTest = 
uuid/local-id of LTP with (LayerProtocolName == AirLayer) AND (ExternalLabel.substring(0,9)==LinkId)
end note

@enduml