@startuml 205_ReadingHistoricalAirInterfacePerformanceFromCache
skinparam responseMessageBelowArrow true

title
RequestForProvidingHistoricalPmDataCausesReadingHistoricalAirInterfacePerformanceFromCache
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-historical-pm-data-of-device" as APTP_Pm
participant "<i>RequestForProvidingHistoricalPmDataCausesReadingLtpStructure</i>" as LTPs
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-historical-performances" as AirInterfacePm

LinkVis -> APTP_Pm: {MountName, timeStamp}<sub>i</sub> (apiKeyAuth)
activate APTP_Pm
LTPs --> APTP_Pm: [{uuid, localId, layerProtocolName}]
loop for each Ltp where LayerProtocolName==AIR_LAYER obtained from RequestForProvidingHistoricalPmDataCausesReadingLtpStructure
    APTP_Pm -> AirInterfacePm: {MountName,uuid,localId} (apiKeyAuth)
    AirInterfacePm --> APTP_Pm: {entire AirInterfaceHistoricalPerformance from cache}
    note over APTP_Pm
    Keep only entries of performance measurements 
    WHERE
    granularity-period == TYPE_PERIOD-15-MIN
    AND
    period-end-time > timeStamp
    Discard the rest
    end note

end

deactivate APTP_Pm

@enduml