@startuml 210_ReadingNameOfAirAndEthernetInterfaces
skinparam responseMessageBelowArrow true

title
RequestForProvidingHistoricalPmDataCausesReadingNameOfAirAndEthernetInterfaces
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-historical-pm-data-of-device" as APTP_Pm
participant "<i>RequestForProvidingHistoricalPmDataCausesReadingLtpStructure</i>" as LTPs
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/\nltp-augment-1-0:ltp-augment-pac?fields=(original-ltp-name;external-label)" as LtpDesignation

LinkVis -> APTP_Pm: {MountName, timeStamp}<sub>i</sub> (apiKeyAuth)
activate APTP_Pm
LTPs --> APTP_Pm: [{uuid, localId, layerProtocolName}]

loop for each Ltp where (layerProtocolName == ("AIR_LAYER" or "ETHERNET_CONTAINER_LAYER"))
    
   
    note over APTP_Pm
    In following Request,
	    IF LayerProtocolName == AIR_LAYER :
	        linkEndPointName = externalLabel
	    ELSE IF LayerProtocolName == ETHERNET_CONTAINER_LAYER :
	        interfaceName = originalLtpName
	end note

    APTP_Pm -> LtpDesignation:{MountName, uuid, localId} (apiKeyAuth)
    LtpDesignation --> APTP_Pm: {originalLtpName, externalLabel}

end

@enduml