@startuml ProvideStatusForLivenetview
skinparam responseMessageBelowArrow true

title
ProvideStatusForLivenetview
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-status-for-livenetview" as APTP_Status
participant "<i>RequestForProvidingStatusForLivenetviewCausesReadingCapabilitiesFromCache</i>" as ReadingCapa
participant "<i>RequestForProvidingStatusForLivenetviewCausesReadingStatusFromLive</i>" as ReadingStatusLive


LinkVis -> APTP_Status: {MountName, LinkId} (apiKeyAuth)

note over APTP_Status
Number of requests to be executed in parallel shall not exceed the value stated in
<b>profile=APTP-1-0-1-integer-p-006</b>
<b>IntegerProfilePac::IntegerProfileConfiguration:integerValue</b>
end note

activate APTP_Status

ReadingCapa --> APTP_Status: {entire AirInterfaceCapability from cache}

ReadingStatusLive --> APTP_Status: {txLevelCur, rxLevelCur, rxFrequencyCur, txFrequencyCur, transmissionModeCur}

note over APTP_Status

Select the TransmissionMode from TransmissionModeList (from <i>ReadingCapabilitiesFromCache</i>)
WHERE transmissionModeName == transmissionModeCur (from <i>ReadingDedicatedStatusFroLive</i>)

CurrentModulation.numberOfStates = TransmissionMode.ModulationScheme
CurrentModulation.nameAtLct = TransmissionMode.modulationSchemeNameAtLct

end note

APTP_Status --> LinkVis: {txLevelCur, rxLevelCur, rxFrequencyCur,txFrequencyCur, \nCurrentModulation.numberOfStates, CurrentModulation.nameAtLct}

deactivate APTP_Status

@enduml