@startuml 00x_CyclicLoadingOfDeviceListFromMwdi
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCausesCyclicLoadingOfDeviceListFromMwdi
end title

participant "RO" as ro
participant "APTP://v1/embed-yourself" as aptp
participant "MWDI://v1/provide-list-of-connected-devices" as mwdi



ro -> aptp
activate aptp

note over aptp
Cyclic operation for 
updating the internal list of devices starts.
To be periodically repeated after the elapsed time period stated in
<b>profile=APTP-1-0-1-integer-p-003</b>
<b>IntegerProfilePac::IntegerProfileConfiguration:integerValue</b>
end note

note over aptp
Get list of connected devices from MWDI and store it internally
end note

aptp -> mwdi
mwdi --> aptp: list of-{mountName}



deactivate aptp

@enduml