@startuml ReadingEquipmentInfoFromCache
skinparam responseMessageBelowArrow true

title
RequestForProvidingEquipmentForLivenetviewCausesReadingEquipmentInfoFromCache
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-equipment-for-livenetview" as liveEquipment
participant "<i>RequestForProvidingEquipmentForLivenetviewCauses\n<i>DeterminingAirInterfaceUuidUnderTest</i>" as InterfaceUnderTest
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}\n/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac?fields=equipment" as EquipmentUuid
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/equipment={uuid}/actual-equipment\n?fields=structure(category);manufactured-thing(equipment-type(type-name;part-type-identifier);equipment-instance(serial-number))" as RadioComponentIdentifiers


LinkVis -> liveEquipment: {MountName, LinkId} (apiKeyAuth)

InterfaceUnderTest --> liveEquipment: {Uuid, LocalId, LayerProtocolName} 

liveEquipment -> EquipmentUuid: {Uuid, LocalId, LayerProtocolName} (apiKeyAuth)
EquipmentUuid --> liveEquipment: list of-{EquipmentUuid}


loop for each EquipmentUuid from list

    liveEquipment -> RadioComponentIdentifiers: {EquipmentUuid} (apiKeyAuth)
    RadioComponentIdentifiers --> liveEquipment: {EquipmentCategory, type-name, serial-number, part-type-identifier}

    note over liveEquipment
    If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT
    radio-equipment-name = type-name
    radio-equipment-serial-number = serial-number
    radio-part-number = part-type-identifier

    If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM
    modem-equipment-name = type-name
    modem-equipment-serial-number = serial-number
    modem-part-number = part-type-identifier

    If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_FULL_OUTDOOR_UNIT
    device-equipment-name = type-name
    device-equipment-serial-number = serial-number
    device-part-number = part-type-identifier
    end note
end
@enduml