@startuml 151_OduConnector
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesDeterminingTheOduConnector
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-acceptance-data-of-link-endpoint" as APTP
participant "MWDI://core-model-1-4:network-control-domain=cache\n/control-construct={mount-name}/logical-termination-point={uuid}\n/ltp-augment-1-0:ltp-augment-pac?fields=equipment;connector" as ConnectorId
participant "MWDI://core-model-1-4:network-control-domain=cache\n/control-construct={mount-name}/equipment={uuid}/connector={local-id}\n?fields=equipment-augment-1-0:connector-pac(sequence-id)" as ConnectorNumber


LinkVis -> APTP: {MountName, LinkId} (apiKeyAuth)
activate APTP

APTP -> ConnectorId: {with uuid of AirInterfaceUnderTest} (apiKeyAuth)
ConnectorId --> APTP: {EquipmentUuidList, ConnectorLocalId}

note over APTP
EquipmentUuidList might contain multiple UUIDs (modem, ODU)
Following request has to be repeated until combination of uuid and local-id leads to connector instance
end note

APTP -> ConnectorNumber: {uuid from EquipmentUuidList, local-id=ConnectorLocalId} (apiKeyAuth)
ConnectorNumber --> APTP: {sequence-id}

note over APTP
connector-plugging-the-outdoor-unit = sequence-id
end note

deactivate APTP

@enduml