@startuml 151_OduConnector
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesDeterminingTheOduConnector
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-acceptance-data-of-link-endpoint" as APTP
participant "<i>RequestForProvidingAcceptanceDataCauses\n<i>DeterminingAirInterfaceUuidUnderTest</i>" as AirInterface
participant "MWDI://core-model-1-4:network-control-domain=cache\n/control-construct={mount-name}/logical-termination-point={uuid}\n/ltp-augment-1-0:ltp-augment-pac?fields=connector-identifier" as ConnectorId
participant "MWDI://core-model-1-4:network-control-domain=cache\n/control-construct={mount-name}/equipment={uuid}/connector={local-id}\n?fields=equipment-augment-1-0:connector-pac(vendor-label)" as ConnectorLabel


LinkVis -> APTP: {MountName, LinkId} (apiKeyAuth)
activate APTP

AirInterface --> APTP: {UuidUnderTest, LocalIdUnderTest}

APTP -> ConnectorId: {MountName, uuid of AirInterfaceUnderTest} (apiKeyAuth)
ConnectorId --> APTP: {ConnectorIdentifier}

note over APTP
    Extract **EquipmentUuid** and **ConnectorLocalId** from ConnectorIdentifier:
    "/core-model-1-4:control-construct/equipment[uuid={**EquipmentUuid**}]/connector[local-id={**ConnectorLocalId**}]"
end note

APTP -> ConnectorLabel: {MountName, EquipmentUuid,ConnectorLocalId} (apiKeyAuth)
ConnectorLabel --> APTP: {vendorLabel}

note over APTP
connector-plugging-the-outdoor-unit = vendorLabel
end note

deactivate APTP

@enduml