@startuml 160_radioComponentIdentifiers
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesReadingTheRadioComponentIdentifiers
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-acceptance-data-of-link-endpoint" as APTP
participant "<i>RequestForProvidingAcceptanceDataCauses\n<i>DeterminingAirInterfaceUuidUnderTest</i>" as AirInterface
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}\n/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac?fields=equipment-identifier" as EquipmentIdentifier
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/equipment={uuid}/actual-equipment\n?fields=structure(category);manufactured-thing(equipment-type(type-name;part-type-identifier);equipment-instance(serial-number))" as RadioComponentIdentifiers

LinkVis -> APTP: {MountName, LinkId} (apiKeyAuth)
activate APTP

AirInterface --> APTP: {UuidUnderTest, LocalIdUnderTest}

APTP -> EquipmentIdentifier: {MountName, UuidUnderTest} (apiKeyAuth)
EquipmentIdentifier --> APTP: listOf-{EquipmentIdentifier}

loop for each EquipmentIndentifer

    note over APTP
        Extract **EquipmentUuid** from EquipmentInstanceIdentifier:
        "/core-model-1-4:control-construct/equipment[uuid='**{EquipmentUuid}**']"
    end note

    APTP -> RadioComponentIdentifiers: {EquipmentUuidList} (apiKeyAuth)
    RadioComponentIdentifiers --> APTP: {EquipmentCategory, type-name, serial-number, part-type-identifier}

    alt 
            note over APTP
                If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT
                radio-equipment-name = type-name
                radio-equipment-serial-number = serial-number
                radio-part-number = part-type-identifier
            end note
    else        
            note over APTP
                If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM
                modem-equipment-name = type-name
                modem-equipment-serial-number = serial-number
                modem-part-number = part-type-identifier
            end note
    else
            note over APTP
                If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_FULL_OUTDOOR_UNIT
                device-equipment-name = type-name
                device-equipment-serial-number = serial-number
                device-part-number = part-type-identifier
            end note
    end alt
end loop


@enduml