@startuml ProvideAcceptanceDataOfLinkEndpoint
skinparam responseMessageBelowArrow true

title
ProvideAcceptanceDataOfLinkEndpoint
end title

participant "LinkVis" as LinkVis
participant "LinkVis://v1/receive-acceptance-\ndata-of-link-endpoint" as LinkVisReceiveAcc
participant "APTP://v1/provide-acceptance-\ndata-of-link-endpoint" as APTP
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeterminingAirInterfaceUnderTest</i>" as LTPs
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingCapabilitiesFromCache</i>" as MwdiCapa
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingConfigurationFromCache</i>" as MwdiConfig
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingDedicatedStatusFromLive</i>" as Status
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>AnalysingTheAggregation</i>" as Aggregation
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingCurrentAlarmsFromLive</i>" as Alarms
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeterminingLanPortRole</i>" as LanPortRole
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeterminingWanPortRole</i>" as WanPortRole
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>RetrievingSpfInformation</i>" as Sfp
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeterminingTheModemPosition</i>" as Modem
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeterminingTheOduConnector</i>" as Odu
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingTheRadioComponentIdentifiers</i>" as RadioComponents
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>ReadingFirmwareList</i>" as Firmware
participant "<i>RequestForProviding\n<i>AcceptanceDataCauses\n<i>DeliveringRequestedAcceptanceData</i>" as Delivery

LinkVis -> APTP: {MountName, LinkId} (apiKeyAuth)

note over APTP
Number of requests to be executed in parallel shall not exceed the value stated in
<b>profile=APTP-1-0-1-integer-p-000</b>
<b>IntegerProfilePac::IntegerProfileConfiguration:integerValue</b>
end note

activate APTP

APTP --> LinkVis: {requestId}


MwdiCapa --> APTP: {entire AirInterfaceCapabilities from cache}
MwdiConfig --> APTP: {entire AirInterfaceConfigurations from cache}
Status --> APTP: {tx-level-cur and rx-level-cur from live}
Aggregation --> APTP: {originalLtpName, externalLabel}
Alarms --> APTP: {entire list of firmware components from cache}
LanPortRole --> APTP: {OriginalLtpName}{VlanInterfaceKind}{interfaceStatus}
WanPortRole --> APTP: {OriginalLtpName}{VlanInterfaceKind}{interfaceStatus}
Sfp --> APTP: {original-ltp-name}{supported-pmd-kind-list.pmd-name}{pmd-kind-cur}
Modem --> APTP: {vendor-label}
Odu --> APTP: {sequence-id}
RadioComponents --> APTP: {EquipmentCategory, type-name, serial-number, part-type-identifier}
Firmware --> APTP: {entire list of firmware components from cache}
Delivery -> LinkVisReceiveAcc: {requestId, structured acceptance data}


deactivate APTP

@enduml