@startuml 01x_Embedding
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCauses...
end title

participant "RO" as RO
participant "ALAP://v1/embed-yourself" as ALAP

RO -> ALAP
activate ALAP

note over ALAP
No individual embedding steps identified
end note

deactivate ALAP

@enduml