@startuml 101_DeterminingAirInterfaceUnderTest
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesDeterminingAirInterfaceUuidUnderTest
end title

participant "LinkVis" as LinkVis
participant "ALAP://v1/provide-acceptance-data-of-link-endpoint" as ALAP
participant "<i>RequestForProvidingAcceptanceDataCausesReadingLtpStructure</i>" as LTPs
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}/\nltp-augment-1-0:ltp-augment-pac?fields=external-label" as ExternalLabel

LinkVis -> ALAP: {MountName, LinkId} (apiKeyAuth)
activate ALAP

LTPs --> ALAP: {Uuid, LocalId, LayerProtocolName}

note over ALAP
For all (UUID, Local-ID)s with LayerProtocolName == AirLayer
until ExternalLabel == LinkId
end note

ALAP -> ExternalLabel: (apiKeyAuth)
ExternalLabel --> ALAP: {ExternalLabel}

note over ALAP
UuidUnderTest/LocalIdUnderTest = 
uuid/local-id of LTP with (LayerProtocolName == AirLayer) AND (ExternalLabel==LinkId)
end note

@enduml