@startuml 120_ReadingCurrentAlarmsFromLive
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesReadingCurrentAlarmsFromLive
end title

participant "LinkVis" as LinkVis
participant "ALAP://v1/provide-acceptance-data-of-link-endpoint" as ALAP
participant "MWDI://core-model-1-4:network-control-domain=live/control-construct={mount-name}/alarms-1-0:alarm-pac/current-alarms" as CurrentAlarms

LinkVis -> ALAP: {MountName, LinkId} (apiKeyAuth)
activate ALAP

ALAP -> CurrentAlarms: (apiKeyAuth)
CurrentAlarms --> ALAP: {entire list of active alarms form live}

@enduml