@startuml 151_OduConnector
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesDeterminingTheOduConnector
end title

participant "LinkVis" as LinkVis
participant "ALAP://v1/provide-acceptance-data-of-link-endpoint" as ALAP
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}\n/logical-termination-point={uuid}/ltp-augment-1-0:ltp-augment-pac?fields=equipment;connector" as ConnectorId
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}\n/equipment={uuid}/connector={local-id}?fields=equipment-augment-1-0:connector-pac(sequence-id)" as ConnectorNumber


LinkVis -> ALAP: {MountName, LinkId} (apiKeyAuth)
activate ALAP

ALAP -> ConnectorId: {with uuid of AirInterfaceUnderTest} (apiKeyAuth)
ConnectorId --> ALAP: {EquipmentUuidList, ConnectorLocalId}

note over ALAP
EquipmentUuidList might contain multiple UUIDs (modem, ODU)
Following request has to be repeated until combination of uuid and local-id leads to connector instance
end note

ALAP -> ConnectorNumber: {uuid from EquipmentUuidList, local-id=ConnectorLocalId} (apiKeyAuth)
ConnectorNumber --> ALAP: {sequence-id}

note over ALAP
connector-plugging-the-outdoor-unit = sequence-id
end note

deactivate ALAP

@enduml