@startuml 152_radioComponentIdentifiers
skinparam responseMessageBelowArrow true

title
RequestForProvidingAcceptanceDataCausesReadingTheRadioComponentIdentifiers
end title

participant "LinkVis" as LinkVis
participant "ALAP://v1/provide-acceptance-data-of-link-endpoint" as ALAP
participant "<i>RequestForProvidingAcceptanceDataCausesDeterminingTheModemPosition</i>" as EquipmentUuid
participant "MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}/equipment={uuid}/actual-equipment\n?fields=structure(category);manufactured-thing(equipment-type(type-name;part-type-identifier);equipment-instance(serial-number))" as RadioComponentIdentifiers

LinkVis -> ALAP: {MountName, LinkId} (apiKeyAuth)
activate ALAP

EquipmentUuid --> ALAP: {EquipmentUuidList}

note over ALAP
For all EquipmentUuids provided in EquipmentUuidList :
end note

ALAP -> RadioComponentIdentifiers: {with uuid from EquipmentUuidList} (apiKeyAuth)
RadioComponentIdentifiers --> ALAP: {EquipmentCategory, type-name, serial-number, part-type-identifier}

note over ALAP
If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT
radio-equipment-name = type-name
radio-equipment-serial-number = serial-number
radio-part-number = part-type-identifier

If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM
modem-equipment-name = type-name
modem-equipment-serial-number = serial-number
modem-part-number = part-type-identifier

If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_FULL_OUTDOOR_UNIT
device-equipment-name = type-name
device-equipment-serial-number = serial-number
device-part-number = part-type-identifier
end note

@enduml