@startuml 307_ReadingEquipmentInfoFromCache
skinparam responseMessageBelowArrow true

title
RequestForProvidingEquipmentForLivenetviewCausesReadingEquipmentInfoFromCache
end title

participant "LinkVis" as LinkVis
participant "APTP://v1/provide-equipment-for-livenetview" as liveEquipment
participant "<i>RequestForProvidingEquipmentForLivenetviewCauses\n<i>DeterminingAirInterfaceUuidUnderTest</i>" as InterfaceUnderTest
participant "MWDI://core-model-1-4:network-control-domain=cache/\ncontrol-construct={mount-name}\n/logical-termination-point={uuid}/\nltp-augment-1-0:ltp-augment-pac?fields=equipment" as EquipmentUuid
participant "MWDI://core-model-1-4:network-control-domain=cache/\ncontrol-construct={mount-name}/equipment={uuid}/\nactual-equipment?fields=structure(category);manufactured-thing\n(equipment-type(type-name;part-type-identifier);\nequipment-instance(serial-number))" as RadioComponentIdentifiers
participant "MWDI://core-model-1-4:network-control-domain=cache/\ncontrol-construct={mount-name}?fields=uuid;\nequipment(contained-holder(occupying-fru;\nequipment-augment-1-0:holder-pac(vendor-label)))" as HolderLabel

LinkVis -> liveEquipment: {MountName, LinkId} (apiKeyAuth)

InterfaceUnderTest --> liveEquipment: {Uuid, LocalId, LayerProtocolName} 

liveEquipment -> EquipmentUuid: {Uuid, LocalId, LayerProtocolName} (apiKeyAuth)
EquipmentUuid --> liveEquipment: list of-{EquipmentUuid}


loop for each EquipmentUuid from list

    liveEquipment -> RadioComponentIdentifiers: {EquipmentUuid} (apiKeyAuth)
    RadioComponentIdentifiers --> liveEquipment: {EquipmentCategory, type-name, serial-number, part-type-identifier}

    alt If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_FULL_OUTDOOR_UNIT
        note over liveEquipment
            device-equipment-name = type-name
            device-equipment-serial-number = serial-number
            device-part-number = part-type-identifier
        end note

    else If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_MODEM
        note over liveEquipment    
            modem-equipment-name = type-name
            modem-equipment-serial-number = serial-number
            modem-part-number = part-type-identifier    
        end note

        liveEquipment -> HolderLabel: (apiKeyAuth)
        HolderLabel --> liveEquipment: {Holder with occupyingFru and label}
        note over liveEquipment    
            **position-of-modem-board = equipment-augment-1-0:holder-pac/vendor-label** for Holder with **occupyingFru == EquipmentUuid**
        end note


    else  If EquipmentCategory == equipment-augment-1-0:EQUIPMENT_CATEGORY_OUTDOOR_UNIT
        note over liveEquipment        
        radio-equipment-name = type-name
        radio-equipment-serial-number = serial-number
        radio-part-number = part-type-identifier
        end note

        liveEquipment -> HolderLabel: (apiKeyAuth)
        HolderLabel --> liveEquipment: {Holder with occupyingFru and label}
        note over liveEquipment    
            **if-port-identifier = equipment-augment-1-0:holder-pac/vendor-label** for Holder with **occupyingFru == EquipmentUuid**
        end note


    end
 

end
@enduml